services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    network_mode: "host"  # Uses the host network
    restart: unless-stopped
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf:ro

  registry:
    image: registry:2
    container_name: docker-registry
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry

volumes:
  registry_data:
