services:
  registry:
    image: registry:2
    container_name: docker-registry
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry

  # loadbalancer:
  #   build: ./loadBalancer
  #   network_mode: "host"

volumes:
  registry_data:
